spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finedb
    username: postgres
    password: Kotresh@123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
